### ISSUE TITLE
Fixing the random state

### ISSUE THREAD

**Issue by johannfaouzi** [angus924/rocket#4]
Hi,

I just wanted to let you know that it is possible to [fix the random seed with Numba](https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#random). The only change would be to add a `seed` parameter to the [generate_kernels](https://github.com/angus924/rocket/blob/531be138f2a8924d1f9549db709b5635361a9d34/code/rocket_functions.py#L10-L35) function:

```python
@njit
def generate_kernels(input_length, num_kernels, seed=42):
    np.random.seed(seed)
```

This way, the results would be perfectly reproducible (as it is, there is randomness when the kernels are generated that cannot be fixed).

Best,
Johann

**Comment by angus924** [comment]
Hi Johann,

Sorry for the slow reply.

This is correct.

This is essentially what I've done for the version going into sktime, curently sitting in a [pull request](https://github.com/alan-turing-institute/sktime/pull/204/files#diff-12a959026990ee7a3744ab3527d8b631R76-R77).

There's a few other little tweaks in there...  I'll reproduce all of those changes / updates in this repository at some stage soon.

Thanks.

Best,

Angus.

**Comment by johannfaouzi** [comment]
Hi Angus,

Thanks for the reply! I've been looking briefly at your PR and the main change that I saw is support for multivariate time series, which is not mentioned in your article. Could you give me more details about this change? Do the different channels share the same kernels or do you create a different kernel for each channel? Did you try to benchmark it on the UEA archive?

As you mentioned it in the comments of your PR, `joblib` will not help you much since it just allows for parallel computing, but will not make the function itself faster. Compiling it using `numba` or `cython` is what will make it fast (and writing `cython` code is not as easy as writing `numba` code...). 

By the way I'm working (locally) on implementing ROCKET and adding it to my package [pyts](https://github.com/johannfaouzi/pyts), that's why I'm asking for more details :) Would you be interested in reviewing it when I'm done? Obviously you don't have to if you don't want, don't have time, etc.

Best,
Johann

Edit: Since dealing with multivariate time series is listed as a future work, I will stick to what is described in your paper for the moment. Here is the [pull request](https://github.com/johannfaouzi/pyts/pull/60):
* [Functions and class](https://github.com/johannfaouzi/pyts/blob/rocket/pyts/transformation/rocket.py)
* [Tests](https://github.com/johannfaouzi/pyts/blob/rocket/pyts/transformation/tests/test_rocket.py)
* [class documentation](https://external-builds.readthedocs.io/html/pyts/60/generated/pyts.transformation.ROCKET.html#pyts.transformation.ROCKET)
* [example](https://external-builds.readthedocs.io/html/pyts/60/auto_examples/transformation/plot_rocket.html#sphx-glr-auto-examples-transformation-plot-rocket-py)

**Comment by johannfaouzi** [comment]
Off topic: did you try to use cost-sensitive learning (i.e. using `class_weight='balanced'` in `RidgeClassifierCV`)?. From my small experiments it seems to increase the accuracy on some datasets, but also to decrease it for other datasets. Maybe it could be useful to add it in the hyper-parameter optimization (it would take two times longer to fit the classifier though).

**Comment by angus924** [comment]
Re multivariate: the multivariate implementation for sktime is a kind of 'placeholder', just so that there is some kind of multivariate funcionality available for the moment, but it's one of several possible ways of making ROCKET work with multivariate time series (and as you note we intend to look at this in more detail in future work).  For this implementation, basically each kernel is randomly assigned to one or more channels (up to a limit).  Apart from the weights (which are different for each channel), everything else about the kernel is the same.  I think that's pretty much all there is to it.

Re pyts: happy to take a look at some point (a bit swamped at the moment), but it should be pretty straightforward to see whether the results are sensible and timings seem roughly ok.

Re class weights: it was a while ago now, but I'm pretty sure I did try it, at least on a few of the datasets.  From (possibly incorrect) memory, a lot of the datasets in the UCR archive are actually not that imbalanced.  In any case, I seem to remember coming to the conclusion that overall it wasn't resulting in a consistent improvement (not just for `RidgeClassifierCV`, but for pretty much anything I tried).

**Comment by johannfaouzi** [comment]
Thanks for the reply! I might merge my PR soon, so you'd have to look at master or the next release if you are still interested and if you have some spare time (I repeat, no obligation at all).

I usually don't run experiments on all the datasets of the UCR archive because most algorithms are computationally expensive and I want users to be able to run the same scripts on their personal computers. Using `class_weight='balanced'` leads to a big decrease in performance for `MiddlePhalanxTW ` but a small increase in performance for `Adiac`. It seems coherent with your results.
